# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
  ...
}:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAHvybwBw1kyBGn0BW_s1RqIpycNjLf_XbE-fpLUF";
    path = fetchgit {
      url = "https://github.com/raysan5/raygui";
      rev = "3b2855842ab578a034f827c38cf8f62c042fc983";
      hash = "sha256-+ZggtQDieitiqNzez0UF55OWd/ijZOBoeV/tBogLzqk=";
    };
  }
  {
    name = "N-V-__8AAJl1DwBezhYo_VE6f53mPVm00R-Fk28NPW7P14EQ";
    path = fetchgit {
      url = "https://github.com/emscripten-core/emsdk";
      rev = "4.0.9";
      hash = "sha256-ftUQjgMio8G3aHIux9ZckJFYq1Vdfkv5w3830XO1Ris=";
    };
  }
  {
    name = "N-V-__8AALShqgXkvqYU6f__FrA22SMWmi2TXCJjNTO1m8XJ";
    path = fetchzip {
      url = "https://pkg.hexops.org/pkg/hexops/xcode-frameworks/8a1cfb373587ea4c9bb1468b7c986462d8d4e10e.tar.gz";
      hash = "sha256-b1Ay3GfBHwubnrGi4lflPiaqGfzWtABEbEiE8+ZTL90=";
    };
  }
  {
    name = "raylib-6.0.0-whq8uCSwLgWWeF3ec3dbG6Rr36SLFL-s2WJ1Q_2E22Bb";
    path = fetchgit {
      url = "https://github.com/raysan5/raylib";
      rev = "6.0";
      hash = "sha256-8+6MDTMc7Spix4ndAUzp51Q5iWcl7pQmyXuV2RutnOk=";
    };
  }
  {
    name = "raylib_zig-6.0.0-KE8RECZ8BQDm-txuospkpZHbJ6DNpacUF7D88RWQ_qAe";
    path = fetchgit {
      url = "https://github.com/raylib-zig/raylib-zig";
      rev = "8758f4cd3a5ae0df6941c4715257223d34c5ad3e";
      hash = "sha256-6Nz8SPLbBmm1Hd58ozqRgBmJAiYor0Fhh9jK+tZz5VU=";
    };
  }
  {
    name = "zemscripten-0.2.0-dev-sRlDqApRAACspTbAZnuNKWIzfWzSYgYkb2nWAXZ-tqqt";
    path = fetchgit {
      url = "https://github.com/zig-gamedev/zemscripten";
      rev = "3fa4b778852226c7346bdcc3c1486e875a9a6d02";
      hash = "sha256-g/sHkcp+zdJEEAaooCS4joPGSij57RVKoLCcef0aRIE=";
    };
  }
  {
    name = "zemscripten-0.2.0-dev-sRlDqEtQAAB_1tPdqJsxQIqXxvvklcFu6VN5p6ANy8hw";
    path = fetchgit {
      url = "https://github.com/zig-gamedev/zemscripten";
      rev = "70bdafc473be2131445bb6fd977fe7cb92fd0f5f";
      hash = "sha256-ZSFoFAS/P7WyvWDOAy3OWNcLer314Ij70oHqrqZQudI=";
    };
  }
]
